"use client"

import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"

import { SmoothScrollbar } from "@14islands/r3f-scroll-rig"

import CanvasEl from "@/components/CanvasEl"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CanvasEl />
        <SmoothScrollbar>
          {(bind) => {
            return (
              <div {...bind} className="container">
                {children}
              </div>
            )
          }}
        </SmoothScrollbar>
      </body>
    </html>
  )
}
